image: python:3.6-slim

before_script:
  - python -V # Print out python version for debugging

stages:
  - test

test_job:
  stage: test
  script:
    - echo "Running tests"
    #- flask test
    - python -m unittest discover -s "./src/tests/"
