# This file is a Ram template
# Image to use
image: "python:3.7" 

#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - cd src/
  - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements.txt

  # Stages in the pipeline
stages:
  - Test

test_job:
  stage: Test
  script:
    - echo "Running tests"
    - flask test