image: python:3
stages:
  - build
  - Test
  - deploy

docker-build:
  image: docker:19.03.12
  stage: build
  services:
  - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker info
  script:
    - docker -v
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

test_flask:
  stage: Test
  before_script:
    - python --version
    - cd src/
    - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements_test.txt
  script:
    - echo "Running tests"
    - flask test

test_flake8:
  stage: Test
  before_script:
    - python --version
    - cd src/
    - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements_test.txt
  script:
    - echo "Running tests"
    - flake8 --statistics --count

deploy-master:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_SHA
    - kubectl get deployment ram-blog || kubectl create deployment ram-blog --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/ram-blog ram-blog="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  only:
    - master