image: python:3
stages:
  - build
  - Test
  - Deploy

docker-build:
  image: docker:stable
  stage: build
  services:
  - name: docker:dind
    alias: thedockerhost
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker -v
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

test_flask:
  stage: Test
  before_script:
    - python --version
    - cd src/
    - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements_test.txt
  script:
    - echo "Running tests"
    - flask test

test_flake8:
  stage: Test
  before_script:
    - python --version
    - cd src/
    - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements_test.txt
  script:
    - echo "Running tests"
    - flake8 --statistics --count

deploy-master:
  stage: Deploy
  image: bitnami/kubectl
  script:
    - kubectl get deployment ram-blog || kubectl create deployment ram-blog --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/ram-blog ram-blog="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  only:
    - master