# This file is a Ram template
# Image to use
image: "python:3.7" 

#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - cd src/
  - pip install --upgrade pip && pip install --no-cache-dir -r ../requirements.txt

  # Stages in the pipeline
stages:
  - Test
  - deploy

test_flask:
  stage: Test
  script:
    - echo "Running tests"
    - flask test

test_flake8:
  stage: Test
  script:
    - echo "Running tests"
    - flake8 --statistics --count

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://kube.tinchoram.com
  when: manual
  only:
    - master